docs_dir: docs/book
site_dir: docs/html
extra:
  project: Development
  current_version: v1
  versions:
    - v1
nav:
  - Home: index.md
  - v1:
      - Introduction: AlmaLinux9/introduction.md
      - Setup:
          - System Requirements: AlmaLinux9/setup/system-requirements.md
          - Installation: AlmaLinux9/setup/installation.md
          - Setup Packages: AlmaLinux9/setup/setup-packages.md
      - Virtualhosts:
          - Overview: AlmaLinux9/virtualhosts/overview.md
          - Create virtualhost: AlmaLinux9/virtualhosts/create-virtualhost.md
      - FAQ: AlmaLinux9/faq.md
site_name: development
site_description: "WSL2 Development Environment"
repo_url: "https://github.com/dotkernel/development"
plugins:
  - search
