---
- name: Setup AlmaLinux9 development environment
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_files:
    - ../../config.yml
    - roles/apache/vars/main.yml
    - roles/system/vars/main.yml
  tasks:
    - name: Check progress
      stat:
        path: "{{ wsl_config_dest }}"
      register: result
    - name: Step 1
      include_role:
        name: "{{ role }}"
        tasks_from: main
      loop:
        - system
      loop_control:
        loop_var: role
      when: not result.stat.exists
    - name: Step 2
      include_role:
        name: "{{ role }}"
        tasks_from: main
      loop:
        - apache
        - php
        - mariadb
        - phpmyadmin
        - composer
        - nodejs
        - git
        - virtualhost
      loop_control:
        loop_var: role
      when: result.stat.exists
