---
- name: Add ppa:ondrej/php repository
  apt_repository:
    repo: ppa:ondrej/php
    update_cache: true
- name: Install PHP 8.4
  apt:
    name:
      - php8.4
      - php8.4-common
      - php8.4-bz2
      - php8.4-cli
      - php8.4-curl
      - php8.4-intl
      - php8.4-mbstring
      - php8.4-mysql
      - php8.4-xml
      - php8.4-zip
      - libapache2-mod-php8.4
    state: present
