---
- name: Install MariaDB 11.4
  command: "dnf install python3-mysqlclient mariadb-server -y"
- name: Enable and start MariaDB service
  command: systemctl enable --now mariadb
- name: Set MariaDB root password
  mysql_user:
    login_user: root
    login_password: "{{ config.mariadb.root_password }}"
    check_implicit_admin: true
    user: root
    password: "{{ config.mariadb.root_password }}"
    host: localhost
