---
- name: Create MariaDB repo file
  template:
    src: "{{ mariadb_repo_src }}"
    dest: "{{ mariadb_repo_dest }}"
    owner: "{{ config.system.username }}"
    group: "{{ config.system.username }}"
- name: Install MariaDB
  ansible.builtin.dnf:
    name:
      - python3-mysqlclient
      - mariadb-server
    state: present
- name: Enable and start MariaDB
  ansible.builtin.service:
    name: mariadb
    enabled: true
    state: started
- name: Set MariaDB root password
  mysql_user:
    login_user: root
    login_password: "{{ config.mariadb.root_password }}"
    check_implicit_admin: true
    name: root
    password: "{{ config.mariadb.root_password }}"
    host: localhost
