---
- name: Install Apache
  dnf:
    name:
      - httpd
      - httpd-tools
    state: latest
- name: Enable and start Apache service
  command: systemctl enable --now httpd
- name: Fix Apache home directory ownership
  file:
    path: "{{ apache_home_dir}}"
    state: directory
    owner: "{{ config.system.username }}"
    group: "{{ config.system.username }}"
