---
- name: Setup AlmaLinux10 development environment
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_files:
    - ./config.yml
    - ./roles/apache/vars/main.yml
  tasks:
    - name: Install and configure packages
      include_role:
        name: "{{ role }}"
        tasks_from: main
      loop:
        - system
        - apache
        - php
        - mariadb
        - phpmyadmin
        - composer
        - nodejs
        - git
        - virtualhost
      loop_control:
        loop_var: role
