---
- name: Create virtualhost directory
  file:
    path: "{{ apache_root_dir }}/{{ virtualhost }}"
    state: directory
    mode: 0755
  loop: "{{ config.virtualhosts }}"
  loop_control:
    loop_var: virtualhost
- name: Create virtualhost/html directory
  file:
    path: "{{ apache_root_dir }}/{{ virtualhost }}/html"
    state: directory
    owner: "{{ config.system.username }}"
    group: "{{ config.system.username }}"
    mode: 0755
  loop: "{{ config.virtualhosts }}"
  loop_control:
    loop_var: virtualhost
- name: Create virtualhost/log directory
  file:
    path: "{{ apache_root_dir }}/{{ virtualhost }}/log"
    state: directory
    mode: 0755
  loop: "{{ config.virtualhosts }}"
  loop_control:
    loop_var: virtualhost
- name: Create virtualhost config file
  template:
    src: virtualhost.conf.j2
    dest: "{{ apache_sites_available }}/{{ virtualhost }}.conf"
  loop: "{{ config.virtualhosts }}"
  loop_control:
    loop_var: virtualhost
- name: Enable virtualhosts
  file:
    src: "{{ apache_sites_available }}/{{ virtualhost }}.conf"
    dest: "{{ apache_sites_enabled }}/{{ virtualhost }}.conf"
    owner: "{{ config.system.username }}"
    group: "{{ config.system.username }}"
    state: link
  loop: "{{ config.virtualhosts }}"
  loop_control:
    loop_var: virtualhost
- name: Reload Apache
  ansible.builtin.systemd_service:
    name: httpd
    state: restarted
